export const DEFAULT_PROMPTS = [
  "speech",
  "music",
  "child singing",
  "male speech, man speaking",
  "child speech, kid speaking",
  "water drops",
  "screaming",
  "silence",
  "dog barking",
  "footsteps",
];

export const DIALOG_MOVIE_PROMPTS = [
  "female speaker, woman speaking",
  "male speaker, man speaking",
  "whispering, soft voice",
  "yelling, shouting",
  "crying, sobbing",
  "laughing, laughter",
  "arguing, fighting",
  "romantic music, passionate music",
  "dramatic music, tension",
  "suspenseful music, thriller",
  "sad music, melancholic",
  "happy music, upbeat",
  "footsteps, walking",
  "door opening, door closing",
  "phone ringing, phone call",
  "silence, quiet",
];

export const ACTION_MOVIE_PROMPTS = [
  "explosion, blast",
  "gun shot, gunfire",
  "gun reloading, loading",
  "automatic weapons, machine gun",
  "punches, hitting, fighting",
  "glass breaking, shatter",
  "car chase, vehicle pursuit",
  "car crash, collision",
  "scream, screaming",
  "man speaking, male voice",
  "woman speaking, female voice",
  "footsteps, running",
  "helicopter, chopper",
  "siren, police siren",
  "tires screeching, skidding",
  "engine revving, car engine",
  "motorcycle, bike",
  "fire, flames",
  "wind, rushing air",
  "dramatic music, orchestral music",
  "silence, quiet",
  "door slam, door",
  "metal impact, clang",
  "water splash, underwater",
];

export const SPORTS_PROMPTS = [
  "crowd cheering, applause",
  "crowd booing",
  "whistle, referee whistle",
  "ball bouncing",
  "ball kick, kick",
  "ball hit, bat hit",
  "announcer, commentator",
  "stadium ambience, crowd noise",
  "horn, air horn",
  "buzzer, game buzzer",
  "running, footsteps",
  "splash, swimming",
  "ice skating, hockey",
  "engine, racing",
  "bicycle, cycling",
  "tennis, racket hit",
  "golf swing, golf",
  "basketball, dribbling",
  "boxing, punching",
  "bell, ring bell",
  "silence, pause",
  "music, intro music",
];

export const MUSIC_DECOMPOSITION_PROMPTS = [
  // Strings
  "violin",
  "viola",
  "cello",
  "double bass, contrabass",
  "acoustic guitar",
  "electric guitar",
  "bass guitar",
  "harp",
  "banjo",
  "mandolin",
  "ukulele",
  // Woodwinds
  "flute",
  "piccolo",
  "clarinet",
  "oboe",
  "bassoon",
  "saxophone, sax",
  "recorder",
  // Brass
  "trumpet",
  "trombone",
  "french horn",
  "tuba",
  "cornet",
  // Percussion
  "drums, drum kit",
  "snare drum",
  "bass drum, kick drum",
  "hi-hat, cymbals",
  "timpani",
  "xylophone",
  "marimba",
  "vibraphone",
  "tambourine",
  "triangle",
  "bongos, congas",
  // Keyboard
  "piano, grand piano",
  "electric piano, keyboard",
  "organ, pipe organ",
  "synthesizer, synth",
  "harpsichord",
  "accordion",
  // Vocals
  "male vocals, male singing",
  "female vocals, female singing",
  "choir, choral",
  "opera singing",
  "beatboxing",
];

// =============================================================================
// SoundCloud-Specific Presets
// =============================================================================

export const SC_TECHNO_PROMPTS = [
  "techno, electronic beat",
  "synthesizer, synth pad",
  "bass drop, sub bass",
  "hi-hat, cymbals",
  "kick drum, bass drum",
  "acid synth, 303",
  "ambient pad, drone",
  "clap, snare",
  "reverb, delay effect",
  "vocal chop, vocal sample",
];

export const SC_CLASSICAL_PROMPTS = [
  "orchestra, orchestral",
  "violin, strings",
  "cello, low strings",
  "piano, grand piano",
  "flute, woodwind",
  "oboe, bassoon",
  "trumpet, brass",
  "timpani, percussion",
  "choir, choral singing",
  "harp, plucked strings",
  "conductor, silence between movements",
  "applause, audience",
];

export const SC_ROCK_PROMPTS = [
  "electric guitar, distorted guitar",
  "bass guitar, bass line",
  "drums, drum kit",
  "snare drum, hi-hat",
  "male vocals, male singing",
  "female vocals, female singing",
  "guitar solo, lead guitar",
  "power chord, heavy guitar",
  "acoustic guitar, clean guitar",
  "crowd cheering, audience",
];

export const SC_JAZZ_PROMPTS = [
  "saxophone, sax solo",
  "trumpet, muted trumpet",
  "piano, jazz piano",
  "double bass, upright bass",
  "drums, brushes on snare",
  "hi-hat, ride cymbal",
  "trombone, brass section",
  "guitar, jazz guitar",
  "vibraphone, mallet",
  "male vocals, scat singing",
  "female vocals, jazz singing",
];

export const SC_HIPHOP_PROMPTS = [
  "rap, rapping",
  "beat, hip hop beat",
  "bass, 808 bass",
  "hi-hat, trap hi-hat",
  "snare, clap",
  "vocal sample, chopped vocals",
  "synthesizer, synth melody",
  "scratch, turntable",
  "ad-lib, shout",
  "silence, pause",
];

export const SC_INSTRUMENTS_PROMPTS = [
  "piano, grand piano",
  "acoustic guitar",
  "electric guitar, distorted guitar",
  "bass guitar, bass",
  "violin, fiddle",
  "cello",
  "drums, drum kit",
  "synthesizer, synth",
  "saxophone, sax",
  "trumpet",
  "flute",
  "organ, keyboard",
  "harp",
  "harmonica",
  "banjo",
  "mandolin",
  "accordion",
  "male vocals, male singing",
  "female vocals, female singing",
  "beatboxing",
];

export const SC_80S_CLASSICS_PROMPTS = [
  "synthesizer, synth pad",
  "drum machine, electronic drums",
  "electric guitar, clean guitar",
  "bass guitar, synth bass",
  "keyboards, electric piano",
  "saxophone, sax solo",
  "male vocals, male singing",
  "female vocals, female singing",
  "choir, backing vocals",
  "handclap, clap",
  "reverb, gated reverb",
  "trumpet, brass section",
];
